### ISSUE TITLE
Switch to Yeoman instead of git clone for creating add-on template?

### ISSUE THREAD

**Issue by pdehaan** [gregglind/shield-study-cli#14]
Not sure if it'd be better to use something like https://www.npmjs.com/package/yo and a custom generator to create a template rather than the current `git clone` approach, which brings in some unwanted keys and files.

I guess it'd depend on whether we could hide the "yo" and generator approach instead of expecting users to globally install a few more dependencies.
But the bright side is that we may be able to prompt users for information (such as versions, author name, repo, etc) rather than having convoluted global defaults.

**Comment by gregglind** [comment]
Agreed thta something _like_ yeoman is also possible.  but if we are doing that, why not fix jpm init?

(If have tried yeoman in the past and not liked it very much.  I am somewhat reliously against question wizards, and tend to yes my way out of them hating them the whole time.  I might be weird in that.  I would rather edit it all in the file.)

**Comment by pdehaan** [comment]
I like `npm init` behavior. I can say `npm init` and go through the wizard and answer questions, or just lazily do `npm init -y` (or maybe `--yes` even) and it will just use defaults.

**Comment by pdehaan** [comment]
Briefly looked into `ember new` last night (which @kumar303 recommends in https://github.com/mozilla/web-ext/issues/540), and it doesn't seem to prompt at all for any user input, and just creates a scaffold (then runs `npm install` and `bower install` automatically to install sub-dependencies).

In fact, I ran `tree` after calling `ember new pantsuit` and got the following results:
- 8,461 directories, 38,314 files (with _./bower_components/_ and _./node_modules/_ directories)
- 44 directories, 155 files (after running `rm -rf node_modules/`)
- 16 directories, 19 files (after running `rm -rf bower_components/`)

**Comment by kumar303** [comment]
The main thing I dislike about `npm init` is it assumes your working directory is where you want all the new files which is a terrible assumption.

**Comment by karuppiah7890** [comment]
@pdehaan I think that's because ember is just huge and overly complex, from what I see in the tutorials, and that's one reason why I never tried to even peek at it. And yeah, I did see many files after doing `ember new` to create an app. But then, Web Extensions won't have so many files. So, I don't think you have to worry about it. And I think something like `npm init` is good. How does [this](https://github.com/mozilla/web-ext/issues/540#issuecomment-251464734) sound for this [issue](https://github.com/mozilla/web-ext/issues/540) ?

**Comment by gregglind** [comment]
Peeps, I am still not convinced that all the machinery of either Yo or Ember new are _worth it_, but I will eat some project init's and see how it goes :)

I really like the desire here to make project init into an awesome process, but I am not sure what the solution to that is.

**Comment by gregglind** [comment]
Would having a 'stable' tag or 'release' or something reduce the fear of getting random / bad versions of the tempate?

**Comment by pdehaan** [comment]
Another thing to potentially look at is [**create-react-app**](https://github.com/facebookincubator/create-react-app).

Notably:
1. https://github.com/facebookincubator/create-react-app#creating-an-app
   
   ``` sh
   $ create-react-app my-app
   $ cd my-app
   ```
   
   > Inside that directory, it will generate the initial project structure **and install the transitive dependencies**.
2. https://github.com/facebookincubator/create-react-app#converting-to-a-custom-setup
   
   > Running `npm run eject` copies all the configuration files and the transitive dependencies (Webpack, Babel, ESLint, etc) right into your project so you have full control over them. Commands like `npm start` and `npm run build` will still work, but they will point to the copied scripts so you can tweak them. At this point, you’re on your own.
3. https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-eject
