### ISSUE TITLE
Add template to CLI repo?

### ISSUE THREAD

**Issue by pdehaan** [gregglind/shield-study-cli#16]
Per [/scripts/initStudy.bash](https://github.com/mozilla/shield-study-cli/blob/master/scripts/initStudy.bash), we're doing a git clone of a remote [**mozilla/shield-studies-addon-template**](https://github.com/mozilla/shield-studies-addon-template) repo.

Not sure if it'd make it simpler if we just included the template in the CLI repo and used some file system "copy" commands or whatever.
#### PROS:
- One less repo to lint and maintain.
- Better control of what files we copy over (ie: .travis.yml and .gitignore and other files that a user may not want).
- Possibly add more logic about the user's local config, versus having weird default repo URLs and author names.
#### CONS:
- probably

**Comment by gregglind** [comment]
I think i am wonfixing this, so that the dev on each piece (can) remain separate.  

With the 'after git' actions the shield-cli does, we can achieve all the pros on this list.

BDFL HAS SPOKEN.  /me shakes stick, blows conch shell.
