### ISSUE TITLE
Version number in package.json templates can be unexpected for new projects

### ISSUE THREAD

**Issue by pdehaan** [gregglind/shield-study-cli#18]
If I understand the flow correctly, we have two different forces at play here...

I use the **shield-study-cli** to create a new shield study, which does a `git clone mozilla/shield-studies-addon-template` to create the scaffolding.

One of the problems is that I'd expect my package.json versioning for a new Shield study to start at a semver logical "0.1.0" or even "1.0.0", but the version number will actually be the semver of the published npm module **shield-studies-addon-template** (which is currently 0.0.2).

Similarly, if we assume that somebody wouldn't want to deploy their shield study to npm, we'd probably want to put a `"private": true` in the package.json, but then that also implies that it'd go in the **shield-studies-addon-template/package.json**. Which I _suppose_ is OK since we may not be publishing to npm if we're relying on installing it via `git clone` versus `npm install` as a dependency somewhere.

**Comment by gregglind** [comment]
I think the right solution here is to have a post-clone script that fixes / removes / blanks  bunch of keys OR a fake .package.json.moustache sort of thing in the template.  

Maybe make a list of what keys we want to 'guess' on?  I this is solveable without going all the way to Yeoman.

**Comment by pdehaan** [comment]
Yeah, I was almost thinking that the package.json can be as basic as:

``` json
{
  "devDependencies": {
    "eslint": "3.7.1",
    "jpm": "1.2.2"
  },
  "engines": {
    "firefox": "38"
  },
  "private": true,
  "scripts": {
    "lint": "eslint .",
    "postinstall": "fixpack",
    "pretest": "npm run lint",
    "test": "node test"
  }
}
```

Then if we run `npm init -y`, it can autofill things like the user's default `name`, `version`, `author`, `keywords`, `license`:

``` json
{
  "name": "shield-init",
  "version": "1.0.0",
  "author": "Peter deHaan (https://about.me/peterdehaan)",
  "devDependencies": {
    "eslint": "3.7.1",
    "jpm": "1.2.2"
  },
  "engines": {
    "firefox": "38"
  },
  "keywords": [],
  "license": "WTFPL",
  "main": "index.js",
  "private": true,
  "scripts": {
    "lint": "eslint .",
    "postinstall": "fixpack",
    "pretest": "npm run lint",
    "test": "node test"
  }
}
```
